= sedjvick
:title: sedjvicksummary
:author: me

:sectnums:

== Анализ

=== Введение

Вводятся понятия, разбирая задачу на связность. Связность транзитивна. Объединение-поиск. Индексы массива - интересующие нас числа. То, что под индексом - указатель на другое число (индекс). Б. Поиск: если все ссылаются на одно и то же число, то они связаны. Б. Объединение: хранится ссылка на следующее число-индекс и так по цепочке развёртывается. Путь можно сжимать пополам `id[i] = id[id[i]]`

=== Принципы анализа

Эмпирический анализ. Данные: случайные, реальный и ошибочные. Оценка и анализ перед реализацией. Рост функций от N. O-нотация. Константы важны и не важны. Пример на линейном и бинарном поиске. Верхняя и нижняя границы эффективности алгоритмов.

== Структуры данных

=== Элементарные типы данных

Строительные блоки - элементарные (базовые) типы данных: символы и числа. Каждая программа - сама тип данных. Функция - тип данных. Описание функций. `typedef`. Разбиение на файлы: интерфейс `.h`, реализацию функций интерфейса `.cpp` и клиенсткую программу, - так, чтобы любую реализацию под интерфейс может было подводить. Классы и структуры.

Массивы - круто. Доступ мгновенный. Решето Эратосфена - пример важности мгновенного доступа. Массив - указатель. Динамическое выделение памяти. Имитация подбрасывания монетки - пример, где используются индексы массива для хранения результатов.

Связные списки - круто. Несколько соглашений, как их организовывать. Операции над списками. Задача Иосифа с циклическим - для примера важности списков. 

Строки - и массив, и указатель. Операции над строками.

Составные структуры данных, например, многомерные массивы (массив строк), мультисписок. Граф в виде матрицы смежности или массива списков смежности.

=== Абстрактные типы данных
=== Рекурсия и деревья
== Сортировка