FROM python

WORKDIR /app

COPY . .

CMD ["python", "index.py"]

# docker build .
# ilyat@DESKTOP : D:\CPP_2022\ed\ed.docker : 02.10.2022 13:46:12
# >  docker image ls
# REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
# <none>       <none>    681a302ddbc3   12 seconds ago   921MB

# ilyat@DESKTOP : D:\CPP_2022\ed\ed.docker : 02.10.2022 13:46:21
# >  docker run 681a302ddbc3
# Hello world!

